(() => {
  'use strict';
  const TV=window.ToonValley,Life=window.ToonValleyLife;if(!TV||!Life)return;const{THREE}=TV,LAKE={x:126,z:-100,rx:25,rz:18};
  const old=TV.scene.children.find(o=>o.isMesh&&o.geometry?.type==='CircleGeometry'&&o.material===TV.materials.water&&Math.hypot(o.position.x+76,o.position.z-45)<3);if(old){old.position.set(-99,TV.terrainHeight(-99,48)+.09,48);old.scale.set(1.25,.76,1);}
  const root=new THREE.Group();root.position.set(LAKE.x,TV.terrainHeight(LAKE.x,LAKE.z)+.18,LAKE.z);TV.scene.add(root);const shore=new THREE.Mesh(new THREE.RingGeometry(19.5,21.2,48),TV.mat(0xd9bd79));shore.rotation.x=-Math.PI/2;shore.scale.set(1.25,.9,1);shore.position.y=.02;root.add(shore);const water=new THREE.Mesh(new THREE.CircleGeometry(20,48),TV.materials.water);water.rotation.x=-Math.PI/2;water.scale.set(1.25,.9,1);water.position.y=.06;root.add(water);
  for(let i=0;i<24;i++){const a=i*Math.PI*2/24,r=new THREE.Mesh(new THREE.CylinderGeometry(.035,.05,1.15+(i%3)*.22,5),TV.materials.green);r.position.set(Math.cos(a)*(20.2+Math.sin(i)*.7)*1.25,.58,Math.sin(a)*(18.1+Math.cos(i)*.4));r.rotation.z=i%2?-.08:.08;root.add(r);}
  const dock=new THREE.Group();dock.position.set(102,TV.terrainHeight(102,-100)+.28,-100);TV.scene.add(dock);for(let i=0;i<10;i++){const p=TV.outlinedMesh(TV.unitBox,TV.materials.wood,1.02);p.scale.set(1.05,.16,3.7);p.position.set(i,.08,0);dock.add(p);}for(const x of[0,3,6,9])for(const z of[-1.7,1.7]){const p=new THREE.Mesh(new THREE.CylinderGeometry(.09,.12,2,6),TV.materials.dark);p.position.set(x,-.55,z);dock.add(p);}const sign=TV.outlinedMesh(TV.unitBox,TV.materials.yellow,1.03);sign.scale.set(2.8,1,.16);sign.position.set(-1.1,1.5,2.15);dock.add(sign);TV.registerInteraction({object:dock,radius:4.2,area:'world',prompt:'Visit Bluebell Lake dock',action:()=>TV.showToast('🌊 Bluebell Lake has a rowboat, reeds, and its own fishing spots.',2.5)});
  const boat=new THREE.Group(),waterY=root.position.y+.14;boat.position.set(112,waterY,-100);boat.rotation.y=Math.PI/2;TV.scene.add(boat);const hull=TV.outlinedMesh(TV.unitBox,TV.materials.wood,1.03);hull.scale.set(4.4,.55,2);hull.position.y=.15;boat.add(hull);for(const z of[-1,1]){const r=TV.outlinedMesh(TV.unitBox,TV.materials.wood,1.02);r.scale.set(4.1,.55,.22);r.position.set(0,.62,z);boat.add(r);}for(const x of[-1.35,0,1.35]){const b=TV.outlinedMesh(TV.unitBox,TV.materials.cream,1.02);b.scale.set(.24,.18,1.7);b.position.set(x,.72,0);boat.add(b);}const bow=TV.outlinedMesh(new THREE.ConeGeometry(1.05,1.8,4),TV.materials.wood,1.03);bow.rotation.z=-Math.PI/2;bow.position.set(2.8,.18,0);boat.add(bow);const oar=new THREE.Mesh(TV.unitBox,TV.materials.wood);oar.scale.set(4.8,.09,.16);oar.position.set(0,.86,0);oar.rotation.y=.35;boat.add(oar);
  const css=document.createElement('style');css.textContent='#bl-controls{position:fixed;z-index:13000;left:50%;bottom:18px;transform:translateX(-50%);background:#fff4d1;border:4px solid #172027;border-radius:16px;box-shadow:0 6px 0 #172027;padding:9px;display:flex;gap:8px;align-items:center;font:800 13px system-ui;color:#172027}#bl-controls button{border:3px solid #172027;border-radius:11px;background:#8fdcff;font-weight:900;padding:9px}';document.head.appendChild(css);
  let riding=false,speed=0,lastFish=-99,clock=0;const keys=Object.create(null);function controls(){document.getElementById('bl-controls')?.remove();const d=document.createElement('div');d.id='bl-controls';d.innerHTML='<span>W/S row · A/D steer</span><button data-fish>🎣 FISH</button><button data-leave>⚓ DOCK</button>';document.body.appendChild(d);d.querySelector('[data-fish]').onclick=fish;d.querySelector('[data-leave]').onclick=leave;}
  function board(){if(riding)return;riding=true;controls();TV.state.seated=false;TV.playerVelocity.set(0,0,0);TV.state.cameraReady=false;TV.showToast('🚣 Row with WASD. Press F to fish and E to return to the dock.',3);}
  function leave(){if(!riding)return;riding=false;speed=0;document.getElementById('bl-controls')?.remove();TV.player.position.set(101,TV.terrainHeight(101,-100),-100);TV.playerVelocity.set(0,0,0);TV.state.grounded=true;TV.state.cameraReady=false;for(const k of Object.keys(keys))delete keys[k];TV.showToast('⚓ Back on the dock.',1.8);}
  function fish(){if(!riding)return;const now=performance.now()/1000;if(now-lastFish<3.5){TV.showToast('Let the water settle for a second.',1.4);return;}lastFish=now;const catches=[['sunfish',18],['bluegill',24],['silver trout',38],['golden carp',55]],pick=catches[Math.floor(Math.random()*catches.length)];Life.addMoney(pick[1],`Bluebell Lake ${pick[0]}`);Life.emitProgress('explore',1,{activity:'boat-fishing',fish:pick[0]});TV.showToast(`🎣 Caught a ${pick[0]}! +$${pick[1]}`,2.4);}
  TV.registerInteraction({object:boat,radius:4,area:'world',prompt:'Board wooden rowboat',enabled:()=>!riding,action:board});document.addEventListener('keydown',e=>{if(!riding)return;if(['KeyW','KeyA','KeyS','KeyD','ArrowUp','ArrowDown','ArrowLeft','ArrowRight','KeyF','KeyE','Space'].includes(e.code)){e.preventDefault();e.stopImmediatePropagation();}if(e.code==='KeyF'&&!e.repeat)return fish();if(e.code==='KeyE'&&!e.repeat)return leave();keys[e.code]=true;},true);document.addEventListener('keyup',e=>{if(riding)keys[e.code]=false;},true);
  TV.registerUpdateHook(dt=>{clock+=dt;water.rotation.z+=dt*.015;boat.position.y=waterY+Math.sin(clock*1.6)*.035;if(!riding)return;const f=(keys.KeyW||keys.ArrowUp?1:0)-(keys.KeyS||keys.ArrowDown?1:0)+Math.max(-1,Math.min(1,TV.state.mobileMoveY||0)),turn=(keys.KeyA||keys.ArrowLeft?1:0)-(keys.KeyD||keys.ArrowRight?1:0)-Math.max(-1,Math.min(1,TV.state.mobileMoveX||0));boat.rotation.y+=turn*dt*1.25*(.45+Math.min(1,Math.abs(speed)/2.5));speed=THREE.MathUtils.damp(speed,Math.max(-1,Math.min(1,f))*5.2,3.4,dt);if(Math.abs(f)<.04)speed=THREE.MathUtils.damp(speed,0,1.8,dt);const nx=boat.position.x+Math.sin(boat.rotation.y)*speed*dt,nz=boat.position.z+Math.cos(boat.rotation.y)*speed*dt,ex=(nx-LAKE.x)/(LAKE.rx-3),ez=(nz-LAKE.z)/(LAKE.rz-2.5);if(ex*ex+ez*ez<1){boat.position.x=nx;boat.position.z=nz;}else speed*=-.18;oar.rotation.y=.35+Math.sin(clock*4.5)*.34*Math.min(1,Math.abs(speed)/2.5);TV.player.position.set(boat.position.x,boat.position.y+.58,boat.position.z);TV.player.rotation.y=boat.rotation.y;TV.playerVelocity.set(0,0,0);TV.state.jumpVelocity=0;TV.state.grounded=true;TV.state.seated=false;TV.state.cameraReady=false;});
  window.ToonValleyBluebellLake=Object.freeze({lake:{...LAKE},counts:{lakes:1,boats:1},legacyPondMoved:!!old,board,leave,fish});console.info('Bluebell Lake ready',window.ToonValleyBluebellLake.counts);
})();
