(() => {
  'use strict';
  const directScript=document.currentScript?.src?.includes('/central-plaza.js');
  const repoBase=window.__TOON_VALLEY_SOURCE_BASE__||'https://raw.githubusercontent.com/XposeMarket/Toon-Valley/main/';
  const localBase=directScript?new URL('.',document.currentScript.src).href:repoBase;
  const files=directScript?['central-plaza-core.js']:['pointer-capture-guard.js','ui-layer-fix.js','central-plaza-core.js','public-interiors.js','moonbeam-theater.js','owned-home.js','world-polish.js','bluebell-lake.js','interaction-world-fix.js','valley-transit.js','community-garden.js','valley-community-life.js','living-interiors.js','navigation-polish.js','side-quest-overhaul.js','side-quest-routine-bridge.js','neighborhood-quests.js','civic-quests.js','side-quest-ui.js','interaction-experience.js','swing-exit-fix.js','npc-building-life.js','mobile-polish.js','camera-experience-polish.js'];
  const loaded={'pointer-capture-guard.js':()=>window.ToonValleyPointerGuard,'ui-layer-fix.js':()=>window.ToonValleyUILayerFix,'central-plaza-core.js':()=>window.ToonValleyCentralPlaza,'public-interiors.js':()=>window.ToonValleyPublicInteriors,'moonbeam-theater.js':()=>window.ToonValleyTheater,'owned-home.js':()=>window.ToonValleyOwnedHome,'world-polish.js':()=>window.ToonValleyWorldPolish,'bluebell-lake.js':()=>window.ToonValleyBluebellLake,'interaction-world-fix.js':()=>window.ToonValleyInteractionFix,'valley-transit.js':()=>window.ToonValleyTransit,'community-garden.js':()=>window.ToonValleyCommunityGarden,'valley-community-life.js':()=>window.ToonValleyCommunityLife,'living-interiors.js':()=>window.ToonValleyLivingInteriors,'navigation-polish.js':()=>window.ToonValleyNavigationPolish,'side-quest-overhaul.js':()=>window.ToonValleySideQuests,'side-quest-routine-bridge.js':()=>window.ToonValleySideQuestRoutineBridge,'neighborhood-quests.js':()=>window.ToonValleyNeighborhoodQuests,'civic-quests.js':()=>window.ToonValleyCivicQuests,'side-quest-ui.js':()=>window.ToonValleySideQuestUI,'interaction-experience.js':()=>window.ToonValleyInteractionExperience,'swing-exit-fix.js':()=>window.ToonValleySwingExitFix,'npc-building-life.js':()=>window.ToonValleyNPCBuildingLife,'mobile-polish.js':()=>window.ToonValleyMobilePolish,'camera-experience-polish.js':()=>window.ToonValleyCameraPolish};
  async function boot(){for(const file of files){if(loaded[file]?.())continue;const url=`${localBase}${file}${directScript?'':`?v=${Date.now()}`}`,response=await fetch(url,{cache:directScript?'default':'no-store'});if(!response.ok)throw new Error(`${file} returned HTTP ${response.status}`);const source=await response.text();new Function(`${source}\n//# sourceURL=toon-valley/${file}`)();}}
  window.ToonValleyExpansionBootstrap=boot();window.ToonValleyExpansionBootstrap.catch(error=>console.error('Toon Valley expansion bootstrap failed',error));
})();