(() => {
'use strict';
if (!window.THREE) { document.querySelector('#load-error').classList.remove('hidden'); return; }
const $=s=>document.querySelector(s), coarse=matchMedia('(pointer:coarse)').matches||navigator.maxTouchPoints>0;
const cfg={mobile:{ratio:.72,far:120,fps:30,trees:45,npcs:6},low:{ratio:1,far:170,fps:45,trees:75,npcs:10},medium:{ratio:1.25,far:220,fps:60,trees:115,npcs:14}};
let quality=coarse?'mobile':'low', started=false, yaw=0,pitch=.1,stamina=1,jump=0,grounded=true,last=performance.now(),lastRender=0,area='world',near=null;
const keys={}, colliders=[], interactables=[], npcs=[];
const scene=new THREE.Scene(); scene.background=new THREE.Color(0x75cfff); scene.fog=new THREE.Fog(0x8fd8f5,65,cfg[quality].far);
const camera=new THREE.PerspectiveCamera(64,innerWidth/innerHeight,.1,260);
const renderer=new THREE.WebGLRenderer({antialias:false,powerPreference:'high-performance',precision:'mediump'}); renderer.outputColorSpace=THREE.SRGBColorSpace; $('#game').append(renderer.domElement);
const ramp=new THREE.DataTexture(new Uint8Array([40,110,190,255]),4,1,THREE.RedFormat); ramp.minFilter=ramp.magFilter=THREE.NearestFilter; ramp.needsUpdate=true;
const M=c=>new THREE.MeshToonMaterial({color:c,gradientMap:ramp}), mats={grass:M(0x78df58),road:M(0x737985),walk:M(0xc8c9bd),dark:M(0x24323b),white:M(0xfff7df),red:M(0xe95757),orange:M(0xff843e),yellow:M(0xffdf45),blue:M(0x4fa8ed),green:M(0x59c66b),pink:M(0xf29abb),purple:M(0x9878d8),wood:M(0x9a6338),skin:M(0xf2ba8c),water:M(0x55bde9),mount:M(0x69aa65)};
scene.add(new THREE.HemisphereLight(0xdaf5ff,0x537c43,2.2)); const sun=new THREE.DirectionalLight(0xfff3c4,2.2);sun.position.set(-50,90,30);scene.add(sun);
function h(x,z){const r=Math.hypot(x,z),flat=Math.min(1,Math.max(0,(r-75)/45));return (Math.sin(x*.05)+Math.cos(z*.045))*.7*flat+Math.max(0,r-125)*.035*flat-.4;}
const groundGeo=new THREE.PlaneGeometry(440,440,42,42);groundGeo.rotateX(-Math.PI/2);for(let i=0;i<groundGeo.attributes.position.count;i++){let x=groundGeo.attributes.position.getX(i),z=groundGeo.attributes.position.getZ(i);groundGeo.attributes.position.setY(i,h(x,z));}groundGeo.computeVertexNormals();scene.add(new THREE.Mesh(groundGeo,mats.grass));
function box(x,y,z,w,hh,d,mat,parent=scene){const o=new THREE.Mesh(new THREE.BoxGeometry(w,hh,d),mat);o.position.set(x,y,z);parent.add(o);return o}
function addCol(x,z,w,d){colliders.push({x,z,w:w/2,d:d/2})}
function blocked(x,z){if(Math.hypot(x,z)>208)return true;for(const c of colliders)if(Math.abs(x-c.x)<c.w+.5&&Math.abs(z-c.z)<c.d+.5)return true;return false}
function road(x,z,w,d){box(x,h(x,z)+.05,z,w,.12,d,mats.road)}
road(0,-2,170,9);road(0,0,9,145);road(0,-38,130,7);road(0,34,130,7);road(-43,0,7,130);road(43,0,7,130);
function building({x,z,w=12,d=10,hgt=7,color=mats.orange,roof=mats.red,name,enter=false}){const y=h(x,z);box(x,y+hgt/2,z,w,hgt,d,color);const r=new THREE.Mesh(new THREE.ConeGeometry(Math.max(w,d)*.72,4,4),roof);r.position.set(x,y+hgt+1.7,z);r.rotation.y=Math.PI/4;scene.add(r);box(x,y+1.7,z+d/2+.05,2.2,3.4,.25,mats.wood);for(const dx of [-w*.28,w*.28])box(x+dx,y+3.7,z+d/2+.08,2.1,1.7,.2,mats.blue);addCol(x,z,w,d);interactables.push({x,z:z+d/2+2.3,r:4,prompt:enter?`Enter ${name}`:`Visit ${name}`,action:()=>toast(enter?`${name} interior is open for exploration in the full build.`:`Welcome to ${name}!`)});}
building({x:0,z:-25,w:20,d:13,hgt:10,color:mats.white,roof:mats.blue,name:'City Hall',enter:true});
box(0,h(0,-25)+14,-25,3,12,3,mats.white); const clock=new THREE.Mesh(new THREE.CylinderGeometry(1.15,1.15,.25,16),mats.yellow);clock.rotation.x=Math.PI/2;clock.position.set(0,h(0,-25)+15,-23.4);scene.add(clock);
building({x:-25,z:-24,color:mats.yellow,roof:mats.orange,name:'Sunny General Store',enter:true});building({x:25,z:-24,color:mats.blue,roof:mats.purple,name:'Storybook Library',enter:true});
building({x:-26,z:22,color:mats.pink,roof:mats.red,name:'Cloud Nine Cafe',enter:true});building({x:26,z:22,color:mats.white,roof:mats.green,name:'Valley Clinic'});
building({x:-62,z:-22,color:mats.red,name:'Fire Station'});building({x:62,z:-22,color:mats.blue,name:'Post Office'});building({x:-61,z:22,color:mats.yellow,name:'Toon Valley School'});building({x:61,z:22,color:mats.purple,name:'Moonlight Theater'});
for(const [x,z,c] of [[-62,52,mats.orange],[-43,52,mats.pink],[-24,52,mats.blue],[24,52,mats.yellow],[43,52,mats.green],[62,52,mats.purple],[-62,-57,mats.blue],[-43,-57,mats.yellow],[-24,-57,mats.pink],[24,-57,mats.green],[43,-57,mats.orange],[62,-57,mats.blue]])building({x,z,w:10,d:9,hgt:6,color:c,roof:mats.red,name:'Home'});
box(0,h(0,7)+.08,7,25,.15,14,mats.walk);const fountain=new THREE.Mesh(new THREE.CylinderGeometry(4,4.6,.8,18),mats.water);fountain.position.set(0,h(0,7)+.5,7);scene.add(fountain);addCol(0,7,8,8);interactables.push({x:0,z:7,r:6,prompt:'Make a wish',action:()=>toast('You tossed an imaginary coin into the fountain!')});
const pond=new THREE.Mesh(new THREE.CircleGeometry(11,24),mats.water);pond.rotation.x=-Math.PI/2;pond.scale.set(1.4,.8,1);pond.position.set(-88,h(-88,48)+.08,48);scene.add(pond);
function tree(x,z,s=1){const y=h(x,z);const g=new THREE.Group();box(0,2*s,0,.8*s,4*s,.8*s,mats.wood,g);for(const [yy,rr] of [[4,2.3],[5.5,1.8]]){const q=new THREE.Mesh(new THREE.IcosahedronGeometry(rr*s,1),mats.green);q.position.y=yy*s;g.add(q)}g.position.set(x,y,z);scene.add(g);addCol(x,z,1.2*s,1.2*s)}
let seed=12345;const rnd=()=>((seed=Math.imul(seed^seed>>>15,1|seed))>>>0)/4294967296;for(let i=0;i<cfg.medium.trees;i++){let a=rnd()*Math.PI*2,r=78+rnd()*115,x=Math.cos(a)*r,z=Math.sin(a)*r;tree(x,z,.7+rnd()*.45)}
for(let i=0;i<18;i++){let a=i/18*Math.PI*2,r=155+((i%3)*13),x=Math.cos(a)*r,z=Math.sin(a)*r;const m=new THREE.Mesh(new THREE.ConeGeometry(14,35,6),mats.mount);m.position.set(x,h(x,z)+17,z);scene.add(m)}
function character(color=mats.orange){const g=new THREE.Group();box(0,1.9,0,1.2,2,.8,color,g);const head=new THREE.Mesh(new THREE.SphereGeometry(.72,10,7),mats.skin);head.position.y=3.45;g.add(head);for(const sx of [-.36,.36]){const leg=box(sx,.55,0,.35,1.1,.4,mats.dark,g);leg.userData.leg=true}return g}
const player=character(mats.orange);player.position.set(0,h(0,55),55);scene.add(player);const vel=new THREE.Vector3();
const npcColors=[mats.pink,mats.blue,mats.green,mats.yellow,mats.purple,mats.red];for(let i=0;i<cfg.medium.npcs;i++){const n=character(npcColors[i%npcColors.length]);n.scale.setScalar(.9);n.position.set((rnd()-.5)*110,h(0,0),(rnd()-.5)*95);n.userData={home:n.position.clone(),phase:rnd()*10};scene.add(n);npcs.push(n)}
function toast(t){const e=$('#toast');e.textContent=t;e.classList.add('show');clearTimeout(toast.t);toast.t=setTimeout(()=>e.classList.remove('show'),2600)}
function applyQuality(q){quality=q;scene.fog.far=cfg[q].far;camera.far=cfg[q].far+35;camera.updateProjectionMatrix();renderer.setPixelRatio(Math.min(devicePixelRatio,cfg[q].ratio));renderer.setSize(innerWidth,innerHeight);$('#quality-label').textContent=q.toUpperCase();document.querySelectorAll('.quality').forEach(b=>b.classList.toggle('active',b.dataset.quality===q));npcs.forEach((n,i)=>n.visible=i<cfg[q].npcs)}
function interact(){if(near)near.action()}
window.addEventListener('keydown',e=>{keys[e.code]=true;if(e.code==='KeyE')interact();if(e.code==='KeyQ')applyQuality(quality==='mobile'?'low':quality==='low'?'medium':'mobile')});window.addEventListener('keyup',e=>keys[e.code]=false);
renderer.domElement.addEventListener('click',()=>{if(started&&!coarse)renderer.domElement.requestPointerLock()});document.addEventListener('mousemove',e=>{if(document.pointerLockElement===renderer.domElement){yaw-=e.movementX*.0024;pitch=Math.max(-.25,Math.min(.42,pitch-e.movementY*.0018))}});
$('#play-button').onclick=()=>{started=true;$('#start-screen').classList.add('hidden');$('#hud').classList.remove('hidden');if(coarse)$('#mobile-controls').classList.remove('hidden');else renderer.domElement.requestPointerLock();};$('#resume-button').onclick=()=>renderer.domElement.requestPointerLock();document.addEventListener('pointerlockchange',()=>{if(started&&!coarse)$('#pause-screen').classList.toggle('hidden',document.pointerLockElement===renderer.domElement)});
document.querySelectorAll('.quality').forEach(b=>b.onclick=()=>applyQuality(b.dataset.quality));
let joyId=null,lookId=null,jx=0,jy=0,lx=0,ly=0;const knob=$('#joystick-knob'),zone=$('#joystick-zone'),look=$('#look-pad');
zone.onpointerdown=e=>{joyId=e.pointerId;zone.setPointerCapture(e.pointerId)};zone.onpointermove=e=>{if(e.pointerId!==joyId)return;const r=zone.getBoundingClientRect(),dx=e.clientX-(r.left+r.width/2),dy=e.clientY-(r.top+r.height/2),m=Math.max(1,Math.hypot(dx,dy)),s=Math.min(42,m);jx=dx/m*s/42;jy=-dy/m*s/42;knob.style.transform=`translate(${jx*42}px,${-jy*42}px)`};zone.onpointerup=()=>{joyId=null;jx=jy=0;knob.style.transform=''};
look.onpointerdown=e=>{lookId=e.pointerId;lx=e.clientX;ly=e.clientY;look.setPointerCapture(e.pointerId)};look.onpointermove=e=>{if(e.pointerId!==lookId)return;yaw-=(e.clientX-lx)*.006;pitch=Math.max(-.25,Math.min(.42,pitch-(e.clientY-ly)*.004));lx=e.clientX;ly=e.clientY};look.onpointerup=()=>lookId=null;
let mobileSprint=false;$('#mobile-sprint').onpointerdown=()=>mobileSprint=true;$('#mobile-sprint').onpointerup=$('#mobile-sprint').onpointercancel=()=>mobileSprint=false;$('#mobile-jump').onpointerdown=()=>{if(grounded){jump=7.3;grounded=false}};$('#mobile-interact').onpointerdown=interact;
function frame(now){requestAnimationFrame(frame);const min=1000/cfg[quality].fps;if(now-lastRender<min)return;lastRender=now;const dt=Math.min(.05,(now-last)/1000);last=now;if(started&&(coarse||document.pointerLockElement===renderer.domElement)){const f=(keys.KeyW?1:0)-(keys.KeyS?1:0)+jy,s=(keys.KeyD?1:0)-(keys.KeyA?1:0)+jx,mag=Math.min(1,Math.hypot(f,s)),run=(keys.ShiftLeft||mobileSprint)&&stamina>.02,spd=run?8:4.6;stamina=Math.max(0,Math.min(1,stamina+dt*(run?-.22:.13)));$('#stamina-fill').style.transform=`scaleX(${stamina})`;const dx=(-Math.sin(yaw)*f+Math.cos(yaw)*s)*spd,dz=(-Math.cos(yaw)*f-Math.sin(yaw)*s)*spd;vel.x=THREE.MathUtils.damp(vel.x,dx,10,dt);vel.z=THREE.MathUtils.damp(vel.z,dz,10,dt);let nx=player.position.x+vel.x*dt,nz=player.position.z+vel.z*dt;if(!blocked(nx,nz)){player.position.x=nx;player.position.z=nz}if(keys.Space&&grounded){jump=7.3;grounded=false;keys.Space=false}jump-=grounded?0:19*dt;player.position.y+=jump*dt;const gy=h(player.position.x,player.position.z);if(player.position.y<=gy){player.position.y=gy;jump=0;grounded=true}if(mag>.05)player.rotation.y=Math.atan2(dx,dz);
near=null;let bd=1e9;for(const it of interactables){let d=Math.hypot(player.position.x-it.x,player.position.z-it.z);if(d<it.r&&d<bd){near=it;bd=d}}$('#interaction-prompt').textContent=near?`${coarse?'USE':'E'} · ${near.prompt}`:'';$('#interaction-prompt').classList.toggle('show',!!near);$('#mobile-interact').classList.toggle('ready',!!near);
for(const n of npcs){n.userData.phase+=dt*.35;const tx=n.userData.home.x+Math.sin(n.userData.phase)*5,tz=n.userData.home.z+Math.cos(n.userData.phase*.8)*5;n.position.x=THREE.MathUtils.damp(n.position.x,tx,1,dt);n.position.z=THREE.MathUtils.damp(n.position.z,tz,1,dt);n.position.y=h(n.position.x,n.position.z)}}
const dist=coarse?6.1:6.8,desired=new THREE.Vector3(player.position.x+Math.sin(yaw)*dist,player.position.y+3.3+pitch*5,player.position.z+Math.cos(yaw)*dist);camera.position.lerp(desired,1-Math.exp(-10*dt));camera.lookAt(player.position.x,player.position.y+1.4+pitch*.7,player.position.z);renderer.render(scene,camera)}
window.onresize=()=>{camera.aspect=innerWidth/innerHeight;camera.updateProjectionMatrix();renderer.setSize(innerWidth,innerHeight)};applyQuality(quality);requestAnimationFrame(frame);
})();
