(() => {
  'use strict';
  const TV=window.ToonValley,Life=window.ToonValleyLife;if(!TV||!Life)return;const{THREE}=TV;
  const DB='toon-valley-save-db',STORE='saves',SLOT='toon-valley-active-slot',EMERGENCY='toon-valley-emergency-save';
  const FILMS=[
    {id:'moon-rabbit',title:'Moon Rabbit Express',tagline:'A tiny rabbit races to catch the last train to the moon.',duration:120},
    {id:'berry-bake',title:'The Great Berry Bake',tagline:'Three berries enter a bakery. Only one cake leaves.',duration:120},
    {id:'bluebell-boat',title:'Boat Day at Bluebell Lake',tagline:'A wooden boat, one stubborn fish, and a perfect afternoon.',duration:120}
  ];
  const key='toon-valley-theater-v1';let state;try{state={selected:FILMS[0].id,visits:0,...JSON.parse(localStorage.getItem(key)||'{}')};}catch{state={selected:FILMS[0].id,visits:0};}
  const saveState=()=>{try{localStorage.setItem(key,JSON.stringify(state));}catch{}};
  const box=(m,x,y,z)=>{const o=TV.outlinedMesh(TV.unitBox,m,1.025);o.scale.set(x,y,z);return o;};
  function add(o,x,y,z){const b=TV.areaBounds.theater;o.position.set(b.cx+x,y,b.cz+z);TV.interiorGroups.theater.add(o);return o;}
  function areaBox(x,z,w,h,d,m,y=h*.5,collider=false){const o=box(m,w,h,d);add(o,x,y,z);if(collider){const b=TV.areaBounds.theater;TV.addBoxCollider(b.cx+x,b.cz+z,w*.5,d*.5,'theater');}return o;}
  if(!TV.areaBounds.theater)TV.areaBounds.theater={cx:895,cz:0,halfW:17,halfD:14};
  if(!TV.interiorGroups.theater){const g=new THREE.Group();g.name='interior-theater';g.visible=false;TV.interiorGroups.theater=g;TV.scene.add(g);}
  TV.setAreaName('theater','MOONBEAM THEATER');TV.createRoom('theater',0x241d36,0x3d2639);
  for(const side of[-1,1]){const f=box(TV.mat(0x241d36),7.35,7.5,.4);f.position.set(895+side*13.5,3.75,14.2);TV.interiorGroups.theater.add(f);}

  const style=document.createElement('style');style.textContent='.mb-overlay{position:fixed;inset:0;z-index:12000;display:grid;place-items:center;background:#0b0d13dd;padding:18px;font-family:system-ui}.mb-panel{width:min(850px,96vw);max-height:88vh;overflow:auto;background:#fff4cf;color:#172027;border:4px solid #172027;border-radius:22px;box-shadow:0 9px 0 #172027;padding:18px;box-sizing:border-box}.mb-head{display:flex;justify-content:space-between;align-items:center}.mb-grid{display:grid;grid-template-columns:repeat(auto-fit,minmax(210px,1fr));gap:12px}.mb-card{background:#fff;border:3px solid #172027;border-radius:18px;padding:14px}.mb-btn{border:3px solid #172027;border-radius:13px;background:#ffcf4a;color:#172027;font-weight:900;padding:10px 12px;box-shadow:0 4px 0 #172027;cursor:pointer}.mb-btn.close{background:#fff}.mb-btn:disabled{opacity:.45}';document.head.appendChild(style);
  let overlay=null;function close(){overlay?.remove();overlay=null;TV.setModalOpen(false);if(TV.DEVICE.touch&&TV.state.started)document.getElementById('mobile-controls')?.classList.remove('hidden');}
  function modal(title,html){close();if(document.pointerLockElement)document.exitPointerLock?.();TV.setModalOpen(true);if(TV.DEVICE.touch)document.getElementById('mobile-controls')?.classList.add('hidden');overlay=document.createElement('div');overlay.className='mb-overlay';overlay.innerHTML=`<section class="mb-panel"><div class="mb-head"><h2>${title}</h2><button class="mb-btn close">✕</button></div>${html}</section>`;overlay.querySelector('.close').onclick=close;document.body.appendChild(overlay);return overlay;}
  async function charge(amount){await Life.saveGame('theater-ticket-sync');const s=Life.getState();if(s.player.money<amount){TV.showToast(`You need $${amount-s.player.money} more.`,2);return false;}s.player.money-=amount;s.player.stats.moneySpent=(s.player.stats.moneySpent||0)+amount;const slot=Math.max(1,Number(localStorage.getItem(SLOT)||1));s.updatedAt=Date.now();try{await new Promise((resolve,reject)=>{const r=indexedDB.open(DB,1);r.onerror=()=>reject(r.error);r.onsuccess=()=>{const db=r.result,tx=db.transaction(STORE,'readwrite');tx.objectStore(STORE).put(s,`slot-${slot}`);tx.oncomplete=()=>{db.close();resolve();};tx.onerror=()=>reject(tx.error);};});}catch(e){console.warn('Ticket save fallback',e);}try{localStorage.setItem(`${EMERGENCY}-${slot}`,JSON.stringify(s));localStorage.setItem(EMERGENCY,JSON.stringify(s));}catch{}await Life.loadGame(slot);return true;}

  areaBox(-9,9.9,5.2,1.35,1.25,TV.materials.purple,.68,true);const reg=new THREE.Group(),rb=box(TV.materials.dark,.9,.5,.65),rs=box(TV.materials.blue,.55,.35,.08);rb.position.y=.25;rs.position.set(0,.62,-.23);reg.add(rb,rs);add(reg,-9,.9,9.8);
  const rug=box(TV.materials.red,14,.06,3.4);add(rug,2,.04,9);for(const[x,c]of[[-5.2,TV.materials.yellow],[0,TV.materials.blue],[5.2,TV.materials.pink]]){const frame=box(TV.materials.wood,3.1,4.2,.18),art=box(c,2.55,3.55,.05);add(frame,x,3.7,13.65);add(art,x,3.7,13.52);}areaBox(-10.5,5.4,12.5,5.8,.45,TV.materials.red,2.9,true);areaBox(10.5,5.4,12.5,5.8,.45,TV.materials.red,2.9,true);const popcorn=areaBox(10.5,10,5.5,1.2,1.2,TV.materials.orange,.6,false);for(let i=0;i<6;i++){const p=new THREE.Mesh(new THREE.SphereGeometry(.14,6,4),TV.materials.yellow);p.position.set(popcorn.position.x-1.5+(i%3)*.7,1.25,popcorn.position.z-.2+Math.floor(i/3)*.35);TV.interiorGroups.theater.add(p);}

  for(const x of[-15,15]){const curtain=box(TV.materials.red,2.1,6.8,.25);add(curtain,x,3.4,-11.8);}const canvas=document.createElement('canvas');canvas.width=640;canvas.height=360;const ctx=canvas.getContext('2d'),texture=new THREE.CanvasTexture(canvas);texture.colorSpace=THREE.SRGBColorSpace;texture.minFilter=THREE.LinearFilter;texture.magFilter=THREE.LinearFilter;const frame=box(TV.materials.dark,12.8,7.2,.3);add(frame,0,4.2,-13.2);const screen=new THREE.Mesh(new THREE.PlaneGeometry(11.9,6.68),new THREE.MeshBasicMaterial({map:texture,color:0xffffff}));screen.position.set(895,4.2,-13.02);TV.interiorGroups.theater.add(screen);
  const seats=[];function sit(seat){TV.state.seated=true;TV.state.seat=seat;TV.playerVelocity.set(0,0,0);TV.state.jumpVelocity=0;TV.state.grounded=true;TV.player.position.set(seat.position.x,.62,seat.position.z-.08);TV.player.rotation.y=Math.PI;TV.state.cameraReady=false;const d=TV.player.userData;d.moving=0;d.bodyRoot.position.y=.08;d.legs[0].rotation.x=d.legs[1].rotation.x=-1.12;d.arms[0].rotation.x=d.arms[1].rotation.x=-.22;TV.showToast(`🎬 ${selected().title} · press E or move to stand`,2.4);}
  for(let r=0;r<4;r++)for(let c=0;c<7;c++){const x=-9+c*3,z=2.8-r*3,g=new THREE.Group(),seat=box(r%2?TV.materials.purple:TV.materials.red,1.55,.35,1.35),back=box(r%2?TV.materials.purple:TV.materials.red,1.55,1.75,.28);seat.position.y=.72;back.position.set(0,1.55,.52);g.add(seat,back);add(g,x,0,z);seats.push(g);if(c===1||c===5)TV.registerInteraction({object:g,radius:1.8,area:'theater',prompt:'Sit for the movie',action:()=>sit(g)});}
  for(const z of[2.8,-.2,-3.2,-6.2])for(const x of[-12.4,12.4]){const aisle=new THREE.Mesh(new THREE.SphereGeometry(.12,6,4),new THREE.MeshBasicMaterial({color:0xffd67b}));add(aisle,x,.15,z);}

  let started=performance.now()/1000,lastDraw=0;const selected=()=>FILMS.find(f=>f.id===state.selected)||FILMS[0];function title(t,y=332,size=22){ctx.font=`900 ${size}px system-ui`;ctx.textAlign='center';ctx.fillStyle='#fff7d8';ctx.strokeStyle='#172027';ctx.lineWidth=6;ctx.strokeText(t,320,y);ctx.fillText(t,320,y);}
  function rabbit(t,s){const p=(t%20)/20;ctx.fillStyle=s<3?'#31578e':'#182548';ctx.fillRect(0,0,640,360);ctx.fillStyle='#f8efb2';ctx.beginPath();ctx.arc(500,80,55+Math.sin(t*.7)*4,0,Math.PI*2);ctx.fill();const x=70+p*500,y=250-Math.sin(p*Math.PI)*90;ctx.fillStyle='#f3f0e5';ctx.beginPath();ctx.arc(x,y,34,0,Math.PI*2);ctx.fill();ctx.beginPath();ctx.ellipse(x-15,y-40,10,28,-.3,0,Math.PI*2);ctx.ellipse(x+14,y-42,10,29,.25,0,Math.PI*2);ctx.fill();if(s>=2){ctx.fillStyle='#d95d57';ctx.fillRect(80,270,480,28);for(let i=0;i<6;i++){ctx.fillStyle=i%2?'#f3c44f':'#77cde3';ctx.fillRect(100+i*78,220,55,48);}}title(['The last train leaves at moonrise!','Hop, hop, hurry!','A tiny ticket for a very big trip.','Next stop: the clouds.','The moon conductor checks every carrot.','Home again before breakfast.'][s]);}
  function berry(t,s){ctx.fillStyle=['#f7cf9c','#ffd9b5','#f2b3c7','#efd06d','#f5c3a7','#f7d9a8'][s];ctx.fillRect(0,0,640,360);ctx.fillStyle='#8f573f';ctx.fillRect(80,250,480,55);for(let i=0;i<3;i++){const x=170+i*150+Math.sin(t*2+i)*15,y=205-Math.abs(Math.sin(t*2.4+i))*55;ctx.fillStyle=['#d94b67','#7552a8','#e25454'][i];ctx.beginPath();ctx.arc(x,y,30,0,Math.PI*2);ctx.fill();}if(s>=3){ctx.fillStyle='#fff0c7';ctx.beginPath();ctx.ellipse(320,218,115,58,0,0,Math.PI*2);ctx.fill();ctx.fillStyle='#f39ab9';ctx.fillRect(240,185,160,60);}title(['Three berries. One impossible recipe.','Flour goes everywhere.','Do not bounce near the mixing bowl.','The cake rises!','A frosting emergency becomes a masterpiece.','Best bake in the whole valley.'][s]);}
  function boatFilm(t,s){const p=(t%20)/20;ctx.fillStyle='#8ed6f2';ctx.fillRect(0,0,640,210);ctx.fillStyle='#5dbf75';ctx.fillRect(0,190,640,70);ctx.fillStyle='#4db9df';ctx.fillRect(0,245,640,115);const x=120+p*380,y=248+Math.sin(t*1.5)*3;ctx.fillStyle='#9a6037';ctx.beginPath();ctx.moveTo(x-65,y);ctx.lineTo(x+65,y);ctx.lineTo(x+42,y+32);ctx.lineTo(x-44,y+32);ctx.closePath();ctx.fill();if(s>=2){const fx=480-Math.sin(t*2)*35,fy=285-Math.abs(Math.sin(t*2))*45;ctx.fillStyle='#ffd04d';ctx.beginPath();ctx.ellipse(fx,fy,24,12,0,0,Math.PI*2);ctx.fill();}title(['Bluebell Lake wakes up early.','Push off from the dock.','Something is nibbling the line.','The fish has other plans.','One slow lap around the reeds.','Sunset makes every boat look heroic.'][s]);}
  function draw(){const f=selected(),elapsed=((performance.now()/1000-started)%120+120)%120,s=Math.floor(elapsed/20)%6;if(f.id==='moon-rabbit')rabbit(elapsed,s);else if(f.id==='berry-bake')berry(elapsed,s);else boatFilm(elapsed,s);ctx.fillStyle='rgba(0,0,0,.45)';ctx.fillRect(0,0,640,40);ctx.fillStyle='#fff';ctx.textAlign='left';ctx.font='800 18px system-ui';ctx.fillText(`${f.title} · ${Math.floor(elapsed/60)}:${String(Math.floor(elapsed%60)).padStart(2,'0')} / 2:00`,18,27);texture.needsUpdate=true;}draw();
  function choose(){const root=modal('Moonbeam Theater Films',`<div class="mb-grid">${FILMS.map(f=>`<article class="mb-card"><h3>🎞️ ${f.title}</h3><p>${f.tagline}</p><b>2:00 short film</b><br><button class="mb-btn" data-film="${f.id}">${f.id===state.selected?'NOW PLAYING':'PLAY THIS FILM'}</button></article>`).join('')}</div>`);root.querySelectorAll('[data-film]').forEach(b=>b.onclick=()=>{state.selected=b.dataset.film;saveState();started=performance.now()/1000;draw();close();TV.showToast(`🎞️ Now playing: ${selected().title}`,2.5);});}TV.registerInteraction({x:886,z:8.7,radius:3.5,area:'theater',prompt:'Choose a short film',action:choose});
  async function ticket(id){close();if(!(await charge(18)))return;state.selected=id;state.visits++;saveState();started=performance.now()/1000;TV.enterInterior('theater',{x:0,z:44.4});Life.emitProgress('explore',1,{activity:'movie-theater'});TV.showToast(`🎟️ Ticket accepted · ${selected().title}`,2.8);}
  function openTickets(){const money=Life.getState().player.money,root=modal('Moonbeam Theater',`<p><b>Three original two-minute Toon Valley shorts are playing. Tickets are $18.</b></p><div class="mb-grid">${FILMS.map(f=>`<article class="mb-card"><h3>🎬 ${f.title}</h3><p>${f.tagline}</p><b>$18 · 2:00</b><br><button class="mb-btn" data-ticket="${f.id}" ${money<18?'disabled':''}>BUY TICKET & ENTER</button></article>`).join('')}</div>`);root.querySelectorAll('[data-ticket]').forEach(b=>b.onclick=()=>ticket(b.dataset.ticket));}
  const outside=TV.interactables.find(i=>i.area==='world'&&i.prompt==='Visit Moonbeam Theater');if(outside){outside.prompt='Buy ticket / see a film';outside.text='Moonbeam Theater is showing original Toon Valley shorts.';outside.action=openTickets;}
  const baseLight=TV.interiorLight.intensity,baseColor=TV.interiorLight.color.clone();let previous=TV.state.area;TV.registerUpdateHook((dt)=>{const area=TV.state.area;if(area==='theater'){TV.interiorLight.intensity=.18;TV.interiorLight.color.setHex(0x7e72b8);lastDraw+=dt;if(lastDraw>=.1){lastDraw=0;draw();}}else if(previous==='theater'){TV.interiorLight.intensity=baseLight;TV.interiorLight.color.copy(baseColor);}previous=area;});
  window.ToonValleyTheater=Object.freeze({films:FILMS.map(f=>({...f})),counts:{films:FILMS.length,seats:seats.length},openTickets,getState:()=>({...state})});console.info('Moonbeam Theater ready',window.ToonValleyTheater.counts);
})();