(()=>{'use strict';const TV=window.ToonValley,Life=window.ToonValleyLife;if(!TV||!Life)return;const{THREE}=TV,root=new THREE.Group();TV.scene.add(root);
const stops=[{name:'Town Square',x:17,z:-8,routeX:17,routeZ:-2,angle:Math.PI/2},{name:'North Homes',x:49,z:58,routeX:43,routeZ:58,angle:Math.PI/2},{name:'Sunshine Park',x:-91,z:40,routeX:-91,routeZ:34,angle:Math.PI/2},{name:'Bluebell Lake',x:72,z:-70,routeX:78,routeZ:-70,angle:-Math.PI/2}],route=[[17,-2],[43,-2],[43,58],[43,34],[-91,34],[-43,34],[-43,-2],[17,-2],[43,-2],[43,-38],[78,-38],[78,-70],[78,-38],[43,-38],[43,-2],[17,-2]],shelterMat=TV.mat(0xf4df9c),routeMat=TV.mat(0x4d91d8),glass=TV.materials.glass;
function benchPoint(s){const lx=.5,lz=-.35,c=Math.cos(s.angle),q=Math.sin(s.angle);return{x:s.x+lx*c+lz*q,z:s.z-lx*q+lz*c}}
for(const s of stops){const g=new THREE.Group();g.position.set(s.x,TV.terrainHeight(s.x,s.z),s.z);g.rotation.y=s.angle;const post=new THREE.Mesh(new THREE.CylinderGeometry(.09,.12,2.6,6),TV.materials.dark);post.position.set(-1.5,1.3,0);g.add(post);const sign=TV.outlinedMesh(TV.unitBox,routeMat,1.025);sign.scale.set(1.35,.75,.12);sign.position.set(-1.5,2.45,0);g.add(sign);const roof=TV.outlinedMesh(TV.unitBox,shelterMat,1.02);roof.scale.set(3.5,.16,1.7);roof.position.set(.5,2.45,0);g.add(roof);const back=new THREE.Mesh(TV.unitBox,glass);back.scale.set(3.3,2.05,.08);back.position.set(.5,1.25,-.78);g.add(back);const bench=TV.outlinedMesh(TV.unitBox,TV.materials.wood,1.02);bench.scale.set(2.3,.22,.55);bench.position.set(.5,.62,-.35);g.add(bench);root.add(g);TV.registerInteraction({x:s.x,z:s.z,radius:4.5,area:'world',prompt:`Wait at ${s.name} shuttle stop`,action:()=>waitAt(s)})}
const bus=new THREE.Group(),body=TV.outlinedMesh(TV.unitBox,routeMat,1.025);body.scale.set(2.45,2.1,5.6);body.position.y=1.55;bus.add(body);const roof=TV.outlinedMesh(TV.unitBox,TV.materials.white,1.02);roof.scale.set(2.3,.45,5.25);roof.position.y=2.82;bus.add(roof);for(const x of[-1.24,1.24])for(const z of[-1.65,0,1.65]){const w=new THREE.Mesh(TV.unitBox,glass);w.scale.set(.08,.78,1.05);w.position.set(x,1.82,z);bus.add(w)}for(const x of[-1.12,1.12])for(const z of[-1.75,1.75]){const w=new THREE.Mesh(new THREE.CylinderGeometry(.47,.47,.3,10),TV.materials.dark);w.rotation.z=Math.PI/2;w.position.set(x,.6,z);bus.add(w)}const windshield=new THREE.Mesh(TV.unitBox,glass);windshield.scale.set(1.75,.82,.08);windshield.position.set(0,1.92,2.86);bus.add(windshield);const dest=TV.outlinedMesh(TV.unitBox,TV.materials.yellow,1.02);dest.scale.set(1.8,.42,.09);dest.position.set(0,2.35,2.9);bus.add(dest);root.add(bus);
let segment=0,progress=0,dwell=0,riding=false,waiting=null,clock=0;const nearest=(x,z)=>{let best=0,dist=1e9;stops.forEach((s,i)=>{const d=Math.hypot(x-s.routeX,z-s.routeZ);if(d<dist){dist=d;best=i}});return{index:best,distance:dist}};const distTo=s=>Math.hypot(bus.position.x-s.routeX,bus.position.z-s.routeZ);
function seatAtStop(s){const p=benchPoint(s);waiting=s;TV.state.seated=true;TV.state.seat={position:{x:p.x,z:p.z},rotation:{y:s.angle+Math.PI},userData:{area:'world',label:'shuttle bench'}};TV.player.position.set(p.x,TV.terrainHeight(p.x,p.z),p.z);TV.player.rotation.y=s.angle+Math.PI;TV.playerVelocity.set(0,0,0);TV.state.jumpVelocity=0;TV.state.grounded=true;TV.state.cameraReady=false}
function waitAt(s){const d=distTo(s),n=nearest(bus.position.x,bus.position.z);if(d<7&&dwell>0&&stops[n.index]===s)return board(s);seatAtStop(s);TV.showToast(`🚌 Waiting at ${s.name}. The shuttle will board you automatically when it arrives.`,2.8)}
function board(s){if(riding||dwell<=0)return;if(TV.state.seated)TV.standUpFromSeat(false);waiting=null;riding=true;TV.playerVelocity.set(0,0,0);TV.state.jumpVelocity=0;TV.state.grounded=true;TV.state.cameraReady=false;TV.showToast(`🚌 Riding from ${s.name}. Press E at a marked stop to get off.`,3);Life.emitProgress('explore',1,{activity:'valley-shuttle'})}
function leaveAt(s){riding=false;TV.player.position.set(s.x,TV.terrainHeight(s.x,s.z),s.z);TV.playerVelocity.set(0,0,0);TV.state.cameraReady=false;TV.showToast(`🚏 Arrived at ${s.name}.`,2)}
document.addEventListener('keydown',e=>{if(!riding||e.code!=='KeyE'||e.repeat)return;const n=nearest(bus.position.x,bus.position.z);if(dwell>0&&n.distance<7){e.preventDefault();e.stopImmediatePropagation();leaveAt(stops[n.index])}else TV.showToast('The shuttle can only stop at marked bus stops.',1.6)},true);
function advance(dt){if(dwell>0){dwell=Math.max(0,dwell-dt);return}const a=route[segment],b=route[(segment+1)%route.length],len=Math.hypot(b[0]-a[0],b[1]-a[1]);progress+=dt*6.4/Math.max(.1,len);if(progress>=1){segment=(segment+1)%route.length;progress=0;const p=route[segment],n=nearest(p[0],p[1]);if(n.distance<1.5)dwell=3.4}const p0=route[segment],p1=route[(segment+1)%route.length];bus.position.x=THREE.MathUtils.lerp(p0[0],p1[0],progress);bus.position.z=THREE.MathUtils.lerp(p0[1],p1[1],progress);bus.position.y=TV.terrainHeight(bus.position.x,bus.position.z)+.22;bus.rotation.y=Math.atan2(p1[0]-p0[0],p1[1]-p0[1])}
TV.registerUpdateHook(dt=>{clock+=dt;advance(dt);body.position.y=1.55+Math.sin(clock*5)*.015;if(waiting){if(!TV.state.seated)waiting=null;else{const p=benchPoint(waiting);TV.player.position.set(p.x,TV.terrainHeight(p.x,p.z),p.z);TV.player.rotation.y=waiting.angle+Math.PI;if(distTo(waiting)<7&&dwell>0)board(waiting)}}if(riding){TV.player.position.set(bus.position.x,bus.position.y+.85,bus.position.z);TV.player.rotation.y=bus.rotation.y;TV.playerVelocity.set(0,0,0);TV.state.jumpVelocity=0;TV.state.grounded=true;TV.state.cameraReady=false}});
window.ToonValleyTransit=Object.freeze({counts:{stops:stops.length,buses:1,routePoints:route.length},stops,route:route.map(p=>p.slice()),bus,waitAt,board,get riding(){return riding},get waiting(){return!!waiting},get stopped(){return dwell>0}});console.info('Valley Shuttle ready',window.ToonValleyTransit.counts)})();